# Generated by Django 5.2 on 2025-05-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_listing_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='tranmission',
            new_name='transmisson',
        ),
    ]
