# Generated by Django 5.2 on 2025-05-24 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_tranmission_listing_transmisson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='transmisson',
            new_name='transmission',
        ),
    ]
